// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojwfubfilcpfneeyuvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvandmdWJmaWxjcGZuZWV5dXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzU1MTQsImV4cCI6MjA2MDgxMTUxNH0.ZeMPPRc4VssvNBMzWJrcWNEeMBUH52uPNWyQucbOoLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);